[platformio]
description = ESP-IDF UART logger with LittleFS web UI for ESP32-S3
default_envs = esp32-s3-idf

[env:esp32-s3-idf]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_deps =
  https://github.com/joltwallet/esp_littlefs.git
build_flags =
  -DAPP_UART_PORT=1
  -DAPP_UART_RX_PIN=18
  -DAPP_UART_TX_PIN=-1
  -DAPP_UART_BAUD=38400
  -DAPP_WEB_START_DELAY_MS=10000
  -DAPP_MAX_AP_CLIENTS=4
